baseurl = "/"
title = "kaveh Diary"
copyright = "© 2018 Copyright kavehmz"
enableRobotsTXT = true
pygmentsCodefences = true 
pygmentsStyle = "native"
publishDir = "./docs/"

theme = "temple"

[params]
  # Enables syntax highlighting
  highlight = true 

  # Supports highlighting for languages not included in the original pack
  # See https://highlightjs.org/download/ for what's included in original pack
  # For reference to all languages, see:
  # https://github.com/isagalaev/highlight.js/tree/master/src/languages
  hjslangs = ["go", "vim"]

  # Enables the topmenu, which pulls from categories
  topmenu = "categories"

# Builds a list page for each category given
[taxonomies]
  tag = "tags"
  category = "categories"

[author]
  name = "Kavehmz"
  github = "kavehmz"
  email = "kavehmz@gmail.com"
  twitter = "kavehmz"
  medium = "kavehmz"